### ISSUE TITLE
Make Jekyll actually work

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/nitrates-phase1#1]
http://ucd-cws.github.io/nitrates-phase1/ is where we will be hosting our website.  There will be a few components.  One, @mclay120 will be making a series of more complete maps.  Also, we need to have live documents pointing to live maps.

Right now I have this little template.
https://github.com/ucd-cws/nitrates-phase1/blob/gh-pages/_layouts/map.html#L7

But, I'd rather have something like this:
https://github.com/ucd-cws/nitrates-phase1/blob/gh-pages/maps/figure3.md

That builds to the complete html file.

And yes maybe an include instead where you can do all:
{% include live-figure
caption="This cool thing"
title="Cool"
services=["http://atlas....","http://atlas"] %}

in our over reaching document.

**Comment by qjhart** [comment]
Also, right now, I just would change a file, and do

``` sh
(jekyll build; cd build; http-server)
```

To test locally.

**Comment by jrmerz** [comment]
@qjhart I have added the map-service template:
https://github.com/ucd-cws/nitrates-phase1/blob/gh-pages/_layouts/service-map.html
which allows you to define services like this:
https://github.com/ucd-cws/nitrates-phase1/blob/gh-pages/maps/fertilizer.html

Let me know how that looks to you.

Also, FYI, **jekyll serve** seems to auto-build and serve the templates.

**Comment by qjhart** [comment]
That works so nice, I'd like an include for the maps.md file, like
{% include figure.html 
caption="Overview of Crop Types" 
figure="figure2.png"
link_to="figure2.html" 
%}

**Comment by qjhart** [comment]
Looking that up, I found this theme: http://hamishwillee.github.io/jekyll-bootstrap-docsite/, do you think we should poach a theme like this as a starting point?

**Comment by jrmerz** [comment]
@qjhart FYI, just pushed cws template.  Still needs work, updates to footer, etc, but it's a start

**Comment by qjhart** [comment]
Looks very nice as is :)
